### PR TITLE
Adding additional fields

### PR DESCRIPTION
**Pull request by lewisvgd**
Allowing to send comments, prodid and varref (the latter are very useful as these show in the transaction list within the realex panel)

### CODE REVIEW

**Comment by coatesap** [comment]
Just because I haven't got the integration guide to hand - could you outline what `prodid` and `varref` are used for?

**Comment by lewisvgd** [comment]
Prodid is the product ID and varref is the variable reference - They dont seem to be on the realex site however, they were in the PDF documentation some time ago.

They are the 2 fields that show in the dashboard against a transaction which makes them very, very useful for the people trying to reconcile transactions.

I've found a reference to them in a 3rd party PDF - I have confirmed that they still exist and work - it just seems that they've been missed out  of the docs.
https://resourcecentre.globaliris.com/documents/pdf.html?id=102

**Comment by coatesap** [comment]
If `prodid` is to do with product IDs - ie. unique identifiers for things in the cart/basket, then shouldn't this be coming from Omnipay\Common\Item (or an appropriately extended equivalent)?

**Comment by lewisvgd** [comment]
I would generally agree however, the realex XML allows for a single prodid per transaction. We could  concatenate all item descriptions but i think the ability to overwrite it in that case would be useful

**Comment by coatesap** [comment]
In that case we have to accept the limitation of the gateway's own API. However I still think the most appropriate place for it to come from is the standard Omnipay cart, even if it means just using the first item from the basket to populate these fields. This will avoid having to add additional non-standard public methods on this driver's classes.

A merchant who would actually make use of these fields, is therefore probably only selling a single item per transaction anyway.

**Comment by lewisvgd** [comment]
Gotcha. In my case there's a "priority" of what should be shown but it's probably too specific to go into the main repo.

**Pull request closed without merging**
